var fs = require('fs');
var convertColors = require('./transformers/colors');
var convertFontSizes = require('./transformers/font-sizes');

var sassVars = '';

sassVars += convertColors();
sassVars += convertFontSizes();
console.log(sassVars);

var comment = `/*
    CAUTION: DO NOT EDIT THIS FILE - It is automatically generated.
    ======================================================
    Design Tokens as SCSS. 
    Source: @adapt-design-system/tokens
*/`;

var outputData = `${comment}\n\n${sassVars}`;

fs.writeFile('./tokens.scss', outputData, function (err) {
    if (err) throw err;
    console.log('Tokens file created successfully.');
});
